// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package capsule

type Uint32Capsule struct {
	s []uint32
}

func NewUint32Capsule() *Uint32Capsule {
	return &Uint32Capsule{s: []uint32{}}
}

func (c *Uint32Capsule) Put(val uint32) {
	c.s = append(c.s, val)
}

func (c *Uint32Capsule) Get() uint32 {
	r := c.s[0]
	c.s = c.s[1:]
	return r
}
